-- JARVIS God Mode — Autonomous Agent Orchestration System
--
-- This schema extends the base JARVIS schema with tables for:
--   - God Mode task tracking (Kanban board)
--   - Agent isolation metadata (worktrees, containers)
--   - Validation pipeline results
--   - Plan approval workflow
--
-- Run with:
--   psql -d jarvis -f scripts/init_godmode_db.sql
--
-- Idempotent: every CREATE uses IF NOT EXISTS.

BEGIN;

-- ─── God Mode Tasks ───────────────────────────────────────────────────────
-- Main table for God Mode task orchestration.
-- Each row represents a high-level task that may spawn multiple sub-agents.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'godmode_status') THEN
    CREATE TYPE godmode_status AS ENUM (
      'backlog',    -- Task created, not yet planned
      'planning',   -- Coordinator generating execution plan
      'pending',    -- Plan generated, awaiting user approval
      'running',    -- Approved, agents executing
      'review',     -- Execution complete, validation in progress
      'done',       -- Validated and merged successfully
      'failed',     -- Validation failed after max retries
      'cancelled'   -- User cancelled
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS god_mode_tasks (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Task metadata
  title           TEXT NOT NULL,
  description     TEXT,
  status          godmode_status NOT NULL DEFAULT 'backlog',
  priority        SMALLINT NOT NULL DEFAULT 100,  -- lower = higher priority

  -- Execution plan (generated by coordinator)
  plan            JSONB,  -- {phases: [{name, steps, estimated_duration_ms, dependencies}]}
  plan_generated_at TIMESTAMPTZ,
  plan_approved   BOOLEAN DEFAULT FALSE,
  plan_approved_at TIMESTAMPTZ,
  plan_approved_by TEXT,  -- user_id or 'auto'

  -- Agent assignment & isolation
  agent_id        TEXT,                    -- unique agent identifier
  worktree_path   TEXT,                    -- /root/Ai-bot/.claude/worktrees/task-{id}
  git_branch      TEXT,                    -- godmode/task-{id}
  base_commit     TEXT,                    -- SHA of base commit
  docker_container_id TEXT,                -- Docker container ID (if sandboxed)

  -- Progress tracking
  current_phase   INTEGER DEFAULT 0,       -- 0-indexed phase number
  total_phases    INTEGER,
  progress_pct    SMALLINT DEFAULT 0,      -- 0-100

  -- Validation results
  validation_score SMALLINT,               -- 0-100 (correctness + completeness + efficiency + safety)
  validation_results JSONB,                -- {syntax, tests, security, logs, breakdown}
  tests_passed    INTEGER,
  tests_total     INTEGER,
  validation_attempts SMALLINT DEFAULT 0,
  max_validation_attempts SMALLINT DEFAULT 3,

  -- Execution results
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ,
  duration_ms     INTEGER,
  output          TEXT,                    -- Final output from agent
  error           TEXT,                    -- Error message if failed
  commits         TEXT[],                  -- Array of commit SHAs produced
  files_changed   TEXT[],                  -- Array of file paths modified

  -- Notifications
  notify_telegram BOOLEAN DEFAULT TRUE,
  last_notified_at TIMESTAMPTZ,
  notification_count INTEGER DEFAULT 0,

  -- Retry & self-healing
  retry_count     SMALLINT DEFAULT 0,
  max_retries     SMALLINT DEFAULT 3,
  last_feedback   TEXT,                    -- Feedback sent to agent on retry

  -- Metadata
  metadata        JSONB DEFAULT '{}'::jsonb,

  -- Soft delete
  deleted_at      TIMESTAMPTZ
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS god_mode_tasks_status_idx
  ON god_mode_tasks(status) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS god_mode_tasks_priority_idx
  ON god_mode_tasks(priority, created_at) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS god_mode_tasks_agent_idx
  ON god_mode_tasks(agent_id) WHERE agent_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS god_mode_tasks_pending_approval_idx
  ON god_mode_tasks(created_at)
  WHERE status = 'pending' AND plan_approved = FALSE AND deleted_at IS NULL;

-- ─── God Mode Phases ──────────────────────────────────────────────────────
-- Detailed tracking of individual phases within a task.
-- Each phase can have its own agent, validation, and results.

CREATE TABLE IF NOT EXISTS god_mode_phases (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id         UUID NOT NULL REFERENCES god_mode_tasks(id) ON DELETE CASCADE,
  phase_number    INTEGER NOT NULL,        -- 0-indexed

  -- Phase definition
  name            TEXT NOT NULL,
  description     TEXT,
  steps           JSONB,                   -- [{step, command, expected_output}]
  estimated_duration_ms INTEGER,
  dependencies    INTEGER[],               -- Array of phase_numbers that must complete first

  -- Execution
  status          TEXT NOT NULL DEFAULT 'pending',  -- pending | running | done | failed
  agent_id        TEXT,
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ,
  duration_ms     INTEGER,

  -- Results
  output          TEXT,
  error           TEXT,
  commits         TEXT[],

  -- Validation
  validation_score SMALLINT,
  validation_results JSONB,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(task_id, phase_number)
);

CREATE INDEX IF NOT EXISTS god_mode_phases_task_idx
  ON god_mode_phases(task_id, phase_number);

-- ─── God Mode Events ──────────────────────────────────────────────────────
-- Audit log of all events in the God Mode system.
-- Used for real-time UI updates, debugging, and analytics.

CREATE TABLE IF NOT EXISTS god_mode_events (
  id              BIGSERIAL PRIMARY KEY,
  ts              TIMESTAMPTZ NOT NULL DEFAULT now(),
  task_id         UUID REFERENCES god_mode_tasks(id) ON DELETE CASCADE,
  phase_id        UUID REFERENCES god_mode_phases(id) ON DELETE CASCADE,

  event_type      TEXT NOT NULL,           -- task_created | plan_generated | plan_approved |
                                           -- agent_started | phase_complete | validation_started |
                                           -- validation_complete | task_complete | task_failed
  actor           TEXT,                    -- user_id | agent_id | 'system'

  data            JSONB,                   -- Event-specific data

  -- For SSE streaming
  notified        BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS god_mode_events_ts_idx ON god_mode_events(ts DESC);
CREATE INDEX IF NOT EXISTS god_mode_events_task_idx ON god_mode_events(task_id, ts DESC);
CREATE INDEX IF NOT EXISTS god_mode_events_type_idx ON god_mode_events(event_type, ts DESC);
CREATE INDEX IF NOT EXISTS god_mode_events_unnotified_idx
  ON god_mode_events(ts) WHERE notified = FALSE;

-- ─── Updated_at triggers ──────────────────────────────────────────────────

DROP TRIGGER IF EXISTS god_mode_tasks_set_updated_at ON god_mode_tasks;
CREATE TRIGGER god_mode_tasks_set_updated_at
  BEFORE UPDATE ON god_mode_tasks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS god_mode_phases_set_updated_at ON god_mode_phases;
CREATE TRIGGER god_mode_phases_set_updated_at
  BEFORE UPDATE ON god_mode_phases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── Helper functions ─────────────────────────────────────────────────────

-- Function to log God Mode events
CREATE OR REPLACE FUNCTION log_godmode_event(
  p_task_id UUID,
  p_event_type TEXT,
  p_actor TEXT DEFAULT 'system',
  p_data JSONB DEFAULT '{}'::jsonb
) RETURNS BIGINT AS $$
DECLARE
  event_id BIGINT;
BEGIN
  INSERT INTO god_mode_events (task_id, event_type, actor, data)
  VALUES (p_task_id, p_event_type, p_actor, p_data)
  RETURNING id INTO event_id;

  RETURN event_id;
END;
$$ LANGUAGE plpgsql;

-- Function to get next pending task (for agent assignment)
CREATE OR REPLACE FUNCTION claim_next_godmode_task(
  p_agent_id TEXT
) RETURNS UUID AS $$
DECLARE
  task_id UUID;
BEGIN
  UPDATE god_mode_tasks
  SET
    agent_id = p_agent_id,
    status = 'running',
    started_at = now(),
    updated_at = now()
  WHERE id = (
    SELECT id FROM god_mode_tasks
    WHERE status = 'pending'
      AND plan_approved = TRUE
      AND deleted_at IS NULL
    ORDER BY priority ASC, created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
  )
  RETURNING id INTO task_id;

  IF task_id IS NOT NULL THEN
    PERFORM log_godmode_event(task_id, 'agent_started', p_agent_id);
  END IF;

  RETURN task_id;
END;
$$ LANGUAGE plpgsql;

COMMIT;
